# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-merge-conflict
  - id: debug-statements
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: pretty-format-json
    args: [--no-sort-keys, --autofix, --no-ensure-ascii]
- repo: https://github.com/adrienverge/yamllint
  rev: v1.37.1
  hooks:
  - id: yamllint
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.3
  hooks:
  - id: ruff-check
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    args: [--autofix]
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint
- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.20.0
  hooks:
  - id: blacken-docs
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: v1.14.2
  hooks:
  - id: zizmor
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
