# -*- coding: UTF-8 -*-
# vim: expandtab sw=4 ts=4 sts=4:
'''
Common data for StarDict[1] convertors.

1. http://stardict.sourceforge.net/
'''
__author__ = 'Michal Čihař'
__email__ = 'michal@cihar.com'
__url__ = 'http:a/cihar.com/software/slovnik/'
__license__ = '''
Copyright (c) 2006 - 2010 Michal Čihař

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see http://www.gnu.org/licenses/.
'''
__revision__ = '1.0'
__header__ = 'GNU/FDL Anglicko-Český slovník to stardict convertor'
# silent pychecker
__pychecker__ = 'unusednames=__license__'


def readme_en(name, url, license, generator, version):
    title = '%s for StarDict' % name
    line = '-' * len(title)
    return '''%s
%s

This is autogenerated dictionary for StarDict.

Data were downloaded from following website:
<%s>

The original source is available under %s.

Dictionary was generated using:
%s version %s

You can get conversion script from:
<http://cihar.com/software/slovnik>

Install dictionary by copying dictionary files to dic/ folder in
StarDict. On Linux it is usually /usr/share/stardict/dic/, on Windows
C:\Program files\stardict\dic\.
''' % (title, line, url, license, generator, version)

def readme_cs(name, url, license, generator, version):
    title = '%s pro StarDict' % name
    line = '-' * len(title)
    return '''%s
%s

Toto je automaticky generovaný slovník pro StarDict.

Data byla stažena z následujících stránek:
<%s>

Původní data jsou dostupná pod %s.

Slovník byl vytvořen za pomoci:
%s verze %s

Skript pro konverzi si můžete stáhnout na:
<http://cihar.com/software/slovnik>

Slovník můžete nainstalovat nakopírováním souborů do adresáře dic/ ve
StarDictu. Na Linuxu to je obvykle /usr/share/stardict/dic/, na Windows
C:\Program files\stardict\dic\.
''' % (title, line, url, license, generator, version)
