# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'
        exclude:
        - os: windows-latest
          python-version: '3.10'
        - os: macos-latest
          python-version: '3.10'
        - os: windows-latest
          python-version: '3.11'
        - os: macos-latest
          python-version: '3.11'
    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}

    steps:
    - run: sudo apt update
      if: matrix.os == 'ubuntu-latest'
    - run: sudo apt install -y dictzip
      if: matrix.os == 'ubuntu-latest'
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        activate-environment: true
    - name: Install pip dependencies
      run: uv sync
    - run: py.test --cov=stardicter
    - run: ./cizislova_tarball.sh --wrap 'coverage run --append'
      if: matrix.os == 'ubuntu-latest'
      continue-on-error: true
    - run: ./dicts_info_tarball.sh --wrap 'coverage run --append' czech german
      if: matrix.os == 'ubuntu-latest'
      continue-on-error: true
    - run: ./slovnik_de_tarball.sh --wrap 'coverage run --append'
      if: matrix.os == 'ubuntu-latest'
      continue-on-error: true
    - run: ./slovnik_tarball.sh --wrap 'coverage run --append'
      if: matrix.os == 'ubuntu-latest'
      continue-on-error: true
    - name: Coverage
      run: coverage xml
    - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        flags: unittests
        name: Python ${{ matrix.python-version }}, ${{ matrix.os }}
